### ISSUE TITLE
Update azblob to 1.1.0 minimum and fix blob-csi.go

### ISSUE THREAD

**Issue by Jose-Matsuda** [StatCan/aaw-kubeflow-profiles-controller#133]
Found as a result of [this issue](https://github.com/StatCan/aaw-private/issues/133) as when we were trying to make updates, these introduced some build errors. When removing `blob-csi` we were able to build just fine and no vulns found. 

The reason for the errors is perhaps some types no longer existing as of v1.1.0 such as `ServiceClient`
![image](https://github.com/StatCan/aaw-kubeflow-profiles-controller/assets/23174198/94f78533-29b0-472a-b113-684b7bf6146b)
So we should
`go get github.com/Azure/azure-sdk-for-go/sdk/storage/asblob@v1.1.0` and then go into the `blob-csi.go` file and then make the modifications necessary.

As of today, [v1.1.0](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go/sdk/storage/azblob) is the latest. The [changelog](https://github.com/Azure/azure-sdk-for-go/blob/main/sdk/storage/azblob/CHANGELOG.md) does indicate breaking changes here and there as well.

**Comment by Souheil-Yazji** [comment]
resolved by https://github.com/StatCan/aaw-kubeflow-profiles-controller/pull/134
