### ISSUE TITLE
Kubeflow Namespaces do not work for new users

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-profiles-controller#17]
@chuckbelisle  and @YannCoderre are my witness; when a user creates a new profile it takes several minutes for

PodDefaults
NetworkPolicies
etc...

to show up. The user has no check-box for Configurations (because of the pod defaults) and notebooks don't work because of the lack of network policies. This is because the profiles-controller is not catching new Profiles quickly enough

My guess is that there is an issue with caching or new thing watched not being added to the cache.

CC @zachomedia @brendangadd

**Comment by blairdrummond** [comment]
@jumana-s

**Comment by chuckbelisle** [comment]
profiles-controller steps for requeue stupidity

statcan/charts
--------------

- add controller settings block to values file
- add env var to all deployment yamls (under templates)
- bump chart version in chart.yaml (eg. from 0.1.8 to 0.1.9)

          env:
            - name: REQUEUE_TIME
              value: {{ .Values.requeue_time }}  >> WRONG

          env:
            - name: REQUEUE_TIME
              value: "{{ .Values.requeue_time }}"  >> WINNING

-- test using $helm -template

statcan/aaw-kubeflow-profiles-controller
----------------------------------------

- load env var for default requeue time (currently set to 5 minutes) (add line at the top of the file right after imports)
  - requeue_time=int(os.Getenv("REQUEUE_TIME"))
- update *.go under ./cmd

-- this will push a new image

statcan/aaw-argocd-manifest
---------------------------

./aaw-argocd-manifests/daaas-system/profile-controllers/profiles-controller/

application.yaml
- update chart # (targetRevision)
- update "tag" value for image
- add env var under values block


-- After changes are made use StatCan/aaw-kubeflow-profiles to add/remove a profile to test new settings --

**Comment by chuckbelisle** [comment]
@blairdrummond the values file to mod in statcan/charts is this one https://github.com/StatCan/charts/blob/master/stable/profiles-controller/values.yaml ?
I also need a refresher on the specifics of the settings block that needs to be added (Need to take better notes)

**Comment by blairdrummond** [comment]
I think you'll need to add a new block called `extraEnv` or something similar, at the top-level of the file

**Comment by skyeturriff** [comment]
There's also the recording!
