### ISSUE TITLE
Add OwnerReference to Gitea controller

### ISSUE THREAD

**Issue by blairdrummond** [StatCan/aaw-kubeflow-profiles-controller#33]
Hey @cboin1996 , I missed this in the first review.

https://github.com/StatCan/aaw-kubeflow-profiles-controller/blob/08689b2e587a0f7514fd649116a61ae9eda2f40a/cmd/gitea.go#L194-L197

We should add an [OwnerRefences](https://kubernetes.io/docs/concepts/architecture/garbage-collection/#owners-dependents) on the gitea objects (all of them).

[Example](https://github.com/StatCan/aaw-kubeflow-profiles-controller/blob/08689b2e587a0f7514fd649116a61ae9eda2f40a/cmd/quotas.go#L197-L199)

**Comment by cboin1996** [comment]
Work is tracked in #
